version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ecommerce_static_volume:/ecommerce/static
      - ecommerce_medias_volume:/ecommerce/media
    networks:
      - nginx_network

volumes:
  ecommerce_static_volume:
    external: true
  ecommerce_medias_volume:
    external: true
networks:
  nginx_network:
    external: true