version: '3.7'

services:
  django_gunicorn:
    container_name: django_gunicorn
    build:
      context: .
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ecommerce_network
      - nginx_network

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - nginx_network

  ecommerce_postgresql:
    image: postgres:14
    container_name: postgresql
    restart: always
    volumes:
      - postgresql_data:/val/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - ecommerce_network

volumes:
  postgresql_data:
    external: true
networks:
  ecommerce_network:
    external: true
  nginx_network:
    external: true