version: '3.7'

services:
  django_gunicorn:
    container_name: django_gunicorn
    build:
      context: .
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn


volumes:
  static: