version: '3.7'

services:
  django_gunicorn:
    container_name: django_gunicorn
    restart: always
    build:
      context: .
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

  ecommerce_postgresql:
    container_name: postgresql
    image: postgres:14
    restart: always
    volumes:
      - postgresql_data:/val/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgresql_data:
    external: true