version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app
    restart: on-failure:10
    volumes:
      - static-data:/vol/web
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data: