version: '3.7'

services:
  django_gunicorn:
    container_name: django_gunicorn
    restart: always
    build:
      context: .
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - nginx_network
#      - postgresql_network
#    links:
#      - ecommerce_postgresql:ecommerce_postgresql
#    depends_on:
#      - ecommerce_postgresql

  nginx:
    container_name: nginx
    build: ./config/nginx
    restart: always
    volumes:
      - ./eCommerce/static_files:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    networks:
      - nginx_network

#  ecommerce_postgresql:
#    container_name: ecommerce_postgresql
#    image: postgres:14
#    restart: always
#    volumes:
#      - postgresql_data:/val/lib/postgresql/data
#    env_file: .env
#    networks:
#      - postgresql_network

volumes:
  postgresql_data:
    external: true
networks:
  nginx_network:
    external: true
#  postgresql_network:
#    driver: bridge