version: '3.7'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
    volumes:
      - static_data:/vol/web
    env_file:
      - .env

  proxy:
    container_name: proxy
    restart: always
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data: